name: Build/Test Pipeline
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Change to sshd-shell-spring-boot-starter directory
        run: cd sshd-shell-spring-boot-starter
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test org.jacoco:jacoco-maven-plugin:report
      - name: Coverall Coverage Report Submission
        run: mvn --batch-mode org.eluder.coveralls:coveralls-maven-plugin:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}